insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('interdum in ante');
insert into Course (title) values ('vel pede');
insert into Course (title) values ('turpis integer aliquet massa');
insert into Course (title) values ('turpis adipiscing lorem vitae mattis');
insert into Course (title) values ('suscipit a feugiat');
insert into Course (title) values ('malesuada in');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('nisi eu orci mauris lacinia');
insert into Course (title) values ('phasellus id sapien');
insert into Course (title) values ('aliquet massa id lobortis convallis');
insert into Course (title) values ('ac nibh');
insert into Course (title) values ('dolor morbi');
insert into Course (title) values ('consectetuer eget');
insert into Course (title) values ('nulla tempus vivamus');
insert into Course (title) values ('mauris eget massa');
insert into Course (title) values ('tortor duis mattis egestas metus');
insert into Course (title) values ('dictumst etiam faucibus cursus urna');
insert into Course (title) values ('ultrices mattis odio donec vitae');
insert into Course (title) values ('in magna bibendum');
insert into Course (title) values ('nulla sed vel');
insert into Course (title) values ('turpis sed ante vivamus tortor');
insert into Course (title) values ('at turpis a pede posuere');
insert into Course (title) values ('libero nullam sit');
insert into Course (title) values ('scelerisque quam');
insert into Course (title) values ('lorem ipsum dolor sit amet');
insert into Course (title) values ('in faucibus orci luctus');
insert into Course (title) values ('massa tempor convallis');
insert into Course (title) values ('sit amet justo morbi ut');
insert into Course (title) values ('tempus semper');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('duis bibendum morbi');
insert into Course (title) values ('nisi venenatis tristique fusce');
insert into Course (title) values ('lacus morbi sem mauris laoreet');
insert into Course (title) values ('magna at nunc commodo placerat');
insert into Course (title) values ('congue eget');
insert into Course (title) values ('hac habitasse platea dictumst');
insert into Course (title) values ('semper rutrum');
insert into Course (title) values ('etiam pretium iaculis justo in');
insert into Course (title) values ('a ipsum integer a nibh');
insert into Course (title) values ('vulputate nonummy maecenas');
insert into Course (title) values ('duis consequat dui nec nisi');
insert into Course (title) values ('risus praesent');
insert into Course (title) values ('justo eu massa donec');
insert into Course (title) values ('integer a nibh in quis');
insert into Course (title) values ('curabitur at ipsum ac');
insert into Course (title) values ('sapien ut nunc vestibulum ante');
insert into Course (title) values ('amet consectetuer adipiscing');
insert into Course (title) values ('odio curabitur convallis');
insert into Course (title) values ('ac consequat metus sapien ut');
insert into Course (title) values ('a odio in');
insert into Course (title) values ('porttitor id consequat');
insert into Course (title) values ('est congue elementum');
insert into Course (title) values ('ornare consequat lectus');
insert into Course (title) values ('nulla neque libero');
insert into Course (title) values ('nunc purus phasellus');
insert into Course (title) values ('quisque ut erat curabitur gravida');
insert into Course (title) values ('neque aenean');
insert into Course (title) values ('orci vehicula condimentum curabitur in');
insert into Course (title) values ('id massa id');
insert into Course (title) values ('justo in');
insert into Course (title) values ('aliquet pulvinar sed nisl nunc');
insert into Course (title) values ('condimentum curabitur in');
insert into Course (title) values ('vulputate ut');
insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('dis parturient montes nascetur ridiculus');
insert into Course (title) values ('vel est donec odio');
insert into Course (title) values ('in felis eu sapien');
insert into Course (title) values ('nunc nisl duis');
insert into Course (title) values ('consectetuer adipiscing elit proin interdum');
insert into Course (title) values ('primis in faucibus');
insert into Course (title) values ('potenti in eleifend');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('diam nam tristique tortor eu');
insert into Course (title) values ('suspendisse potenti');
insert into Course (title) values ('ante ipsum primis in faucibus');
insert into Course (title) values ('nibh ligula nec sem duis');
insert into Course (title) values ('ut volutpat');
insert into Course (title) values ('sagittis sapien cum sociis natoque');
insert into Course (title) values ('iaculis diam');
insert into Course (title) values ('ante ipsum primis in faucibus');
insert into Course (title) values ('aliquam convallis nunc');
insert into Course (title) values ('erat eros viverra eget');
insert into Course (title) values ('congue elementum in hac habitasse');
insert into Course (title) values ('vel accumsan tellus nisi');
insert into Course (title) values ('nulla tellus');
insert into Course (title) values ('cras in');
insert into Course (title) values ('in sapien');
insert into Course (title) values ('dictumst aliquam augue quam sollicitudin');
insert into Course (title) values ('lobortis convallis');
insert into Course (title) values ('ante vestibulum');
insert into Course (title) values ('integer a nibh');
insert into Course (title) values ('mi nulla');
insert into Course (title) values ('dapibus augue vel');
insert into Course (title) values ('sed tristique in tempus');
insert into Course (title) values ('donec ut mauris eget');
insert into Course (title) values ('turpis nec euismod scelerisque quam');
insert into Course (title) values ('sed lacus morbi sem');
insert into Course (title) values ('et ultrices');
insert into Course (title) values ('proin risus praesent');
insert into Course (title) values ('lacus morbi');
insert into Course (title) values ('ultrices erat tortor sollicitudin');
insert into Course (title) values ('curae nulla dapibus dolor');
insert into Course (title) values ('integer pede');
insert into Course (title) values ('ridiculus mus vivamus vestibulum');
insert into Course (title) values ('ipsum aliquam non');
insert into Course (title) values ('suscipit a feugiat et');
insert into Course (title) values ('cursus urna');
insert into Course (title) values ('tincidunt in leo maecenas pulvinar');
insert into Course (title) values ('amet eros');
insert into Course (title) values ('mauris ullamcorper purus');
insert into Course (title) values ('vel augue vestibulum');
insert into Course (title) values ('ultrices posuere cubilia');
insert into Course (title) values ('nullam varius nulla facilisi');
insert into Course (title) values ('velit eu');
insert into Course (title) values ('nam ultrices libero non');
insert into Course (title) values ('nisi at nibh');
insert into Course (title) values ('ipsum dolor');
insert into Course (title) values ('ultrices posuere cubilia');
insert into Course (title) values ('ipsum ac');
insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('montes nascetur');
insert into Course (title) values ('justo in hac habitasse');
insert into Course (title) values ('orci pede venenatis non');
insert into Course (title) values ('libero nullam sit amet turpis');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('nulla dapibus');
insert into Course (title) values ('rhoncus dui vel sem sed');
insert into Course (title) values ('sagittis nam congue risus semper');
insert into Course (title) values ('justo nec condimentum neque sapien');
insert into Course (title) values ('ipsum integer a nibh in');
insert into Course (title) values ('donec dapibus duis at velit');
insert into Course (title) values ('neque libero');
insert into Course (title) values ('sed vestibulum sit amet cursus');
insert into Course (title) values ('sagittis dui vel');
insert into Course (title) values ('ut odio cras mi');
insert into Course (title) values ('aliquam erat volutpat in');
insert into Course (title) values ('est donec odio justo sollicitudin');
insert into Course (title) values ('in faucibus');
insert into Course (title) values ('consequat lectus');
insert into Course (title) values ('risus semper porta');
insert into Course (title) values ('lorem ipsum dolor sit');
insert into Course (title) values ('nam congue risus semper porta');
insert into Course (title) values ('ipsum aliquam non mauris');
insert into Course (title) values ('dapibus duis at velit eu');
insert into Course (title) values ('ipsum dolor sit amet consectetuer');
insert into Course (title) values ('diam nam tristique');
insert into Course (title) values ('aliquet pulvinar');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('ultricies eu');
insert into Course (title) values ('nec nisi volutpat eleifend donec');
insert into Course (title) values ('hac habitasse');
insert into Course (title) values ('vel pede morbi porttitor lorem');
insert into Course (title) values ('elit proin interdum mauris non');
insert into Course (title) values ('et magnis dis parturient montes');
insert into Course (title) values ('nisi vulputate nonummy');
insert into Course (title) values ('orci luctus');
insert into Course (title) values ('varius integer ac leo pellentesque');
insert into Course (title) values ('in lacus curabitur');
insert into Course (title) values ('consectetuer eget rutrum at');
insert into Course (title) values ('augue luctus');
insert into Course (title) values ('risus dapibus augue vel');
insert into Course (title) values ('rhoncus sed vestibulum');
insert into Course (title) values ('justo sit');
insert into Course (title) values ('nulla nisl nunc nisl');
insert into Course (title) values ('vestibulum ante ipsum primis in');
insert into Course (title) values ('montes nascetur');
insert into Course (title) values ('vestibulum ante');
insert into Course (title) values ('massa quis');
insert into Course (title) values ('cursus id turpis integer');
insert into Course (title) values ('ac tellus semper interdum mauris');
insert into Course (title) values ('magna vestibulum aliquet ultrices');
insert into Course (title) values ('aenean auctor gravida sem praesent');
insert into Course (title) values ('ultrices posuere cubilia curae');
insert into Course (title) values ('tortor id nulla ultrices aliquet');
insert into Course (title) values ('justo maecenas rhoncus');
insert into Course (title) values ('ac nulla sed vel enim');
insert into Course (title) values ('aliquet massa id');
insert into Course (title) values ('augue vestibulum ante ipsum');
insert into Course (title) values ('ultrices posuere cubilia curae mauris');
insert into Course (title) values ('est et tempus semper');
insert into Course (title) values ('adipiscing lorem vitae mattis');
insert into Course (title) values ('tempus semper');
insert into Course (title) values ('ligula nec sem duis');
insert into Course (title) values ('ut at dolor');
insert into Course (title) values ('a pede posuere');
insert into Course (title) values ('id ornare imperdiet');
insert into Course (title) values ('lacinia nisi');
insert into Course (title) values ('dapibus duis');
insert into Course (title) values ('proin eu mi');
insert into Course (title) values ('sapien dignissim vestibulum vestibulum');
insert into Course (title) values ('vel pede');
insert into Course (title) values ('elementum pellentesque');
insert into Course (title) values ('nisi vulputate');
insert into Course (title) values ('vulputate vitae nisl aenean lectus');
insert into Course (title) values ('eget semper');
insert into Course (title) values ('mattis egestas metus aenean');
insert into Course (title) values ('faucibus orci luctus et ultrices');
insert into Course (title) values ('amet eros suspendisse accumsan tortor');
insert into Course (title) values ('in porttitor');
insert into Course (title) values ('bibendum imperdiet');
insert into Course (title) values ('et ultrices posuere cubilia');
insert into Course (title) values ('sollicitudin vitae consectetuer eget');
insert into Course (title) values ('augue vestibulum rutrum rutrum');
insert into Course (title) values ('ut nunc');
insert into Course (title) values ('elementum in hac habitasse platea');
insert into Course (title) values ('nulla neque');
insert into Course (title) values ('turpis enim blandit mi in');
insert into Course (title) values ('vivamus vestibulum sagittis');
insert into Course (title) values ('sodales scelerisque');
insert into Course (title) values ('nullam porttitor lacus');
insert into Course (title) values ('ut erat curabitur');
insert into Course (title) values ('amet sapien');
insert into Course (title) values ('sed vestibulum sit');
insert into Course (title) values ('in hac habitasse platea dictumst');
insert into Course (title) values ('morbi non lectus aliquam sit');
insert into Course (title) values ('lectus aliquam sit');
insert into Course (title) values ('sapien cursus vestibulum proin eu');
insert into Course (title) values ('nulla justo');
insert into Course (title) values ('libero rutrum ac');
insert into Course (title) values ('mauris non');
insert into Course (title) values ('et ultrices posuere cubilia curae');
insert into Course (title) values ('aliquam augue quam sollicitudin vitae');
insert into Course (title) values ('nisl nunc rhoncus');
insert into Course (title) values ('purus aliquet at feugiat');
insert into Course (title) values ('ligula nec sem duis aliquam');
insert into Course (title) values ('ac est lacinia nisi venenatis');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('quis turpis eget elit');
insert into Course (title) values ('justo sollicitudin ut');
insert into Course (title) values ('nonummy integer non velit');
insert into Course (title) values ('justo in');
insert into Course (title) values ('nullam varius nulla facilisi');
insert into Course (title) values ('pellentesque ultrices phasellus');
insert into Course (title) values ('interdum mauris non ligula pellentesque');
insert into Course (title) values ('adipiscing elit');
insert into Course (title) values ('porta volutpat quam pede lobortis');
insert into Course (title) values ('amet lobortis');
insert into Course (title) values ('morbi porttitor lorem id ligula');
insert into Course (title) values ('in faucibus orci');
insert into Course (title) values ('vestibulum eget vulputate');
insert into Course (title) values ('blandit nam nulla integer pede');
insert into Course (title) values ('parturient montes nascetur');
insert into Course (title) values ('faucibus orci luctus et');
insert into Course (title) values ('arcu libero');
insert into Course (title) values ('integer pede justo lacinia');
insert into Course (title) values ('vestibulum ante ipsum primis in');
insert into Course (title) values ('ultrices erat tortor sollicitudin');
insert into Course (title) values ('integer pede justo');
insert into Course (title) values ('eget orci vehicula condimentum curabitur');
insert into Course (title) values ('nulla eget');
insert into Course (title) values ('quisque erat eros');
insert into Course (title) values ('eget tempus');
insert into Course (title) values ('integer tincidunt');
insert into Course (title) values ('maecenas leo');
insert into Course (title) values ('cursus id turpis');
insert into Course (title) values ('nulla eget eros elementum');
insert into Course (title) values ('at velit vivamus vel nulla');
insert into Course (title) values ('suspendisse ornare consequat');
insert into Course (title) values ('odio porttitor id');
insert into Course (title) values ('lobortis vel dapibus');
insert into Course (title) values ('hendrerit at');
insert into Course (title) values ('molestie nibh');
insert into Course (title) values ('ac leo pellentesque');
insert into Course (title) values ('nulla tempus');
insert into Course (title) values ('justo in');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('in hac');
insert into Course (title) values ('donec pharetra magna vestibulum aliquet');
insert into Course (title) values ('nulla mollis molestie');
insert into Course (title) values ('magna vulputate luctus cum');
insert into Course (title) values ('eros elementum pellentesque quisque porta');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('lectus vestibulum');
insert into Course (title) values ('velit vivamus vel nulla eget');
insert into Course (title) values ('lectus pellentesque at nulla');
insert into Course (title) values ('sit amet eleifend pede libero');
insert into Course (title) values ('lectus suspendisse');
insert into Course (title) values ('sociis natoque penatibus');
insert into Course (title) values ('in felis eu');
insert into Course (title) values ('aenean lectus pellentesque eget nunc');
insert into Course (title) values ('morbi quis tortor id nulla');
insert into Course (title) values ('diam in magna bibendum');
insert into Course (title) values ('blandit ultrices');
insert into Course (title) values ('justo in blandit ultrices');
insert into Course (title) values ('euismod scelerisque quam turpis');
insert into Course (title) values ('natoque penatibus et magnis');
insert into Course (title) values ('mus etiam vel');
insert into Course (title) values ('aenean auctor');
insert into Course (title) values ('ante ipsum primis');
insert into Course (title) values ('felis eu');
insert into Course (title) values ('vitae ipsum aliquam non mauris');
insert into Course (title) values ('at turpis donec posuere');
insert into Course (title) values ('ultrices libero');
insert into Course (title) values ('ut nulla');
insert into Course (title) values ('morbi vel');
insert into Course (title) values ('euismod scelerisque quam');
insert into Course (title) values ('iaculis justo');
insert into Course (title) values ('ut massa');
insert into Course (title) values ('ultrices libero non mattis');
insert into Course (title) values ('amet consectetuer adipiscing elit');
insert into Course (title) values ('dui proin leo odio porttitor');
insert into Course (title) values ('libero convallis eget eleifend');
insert into Course (title) values ('diam erat fermentum justo');
insert into Course (title) values ('pellentesque eget nunc');
insert into Course (title) values ('nulla ac enim');
insert into Course (title) values ('parturient montes nascetur ridiculus');
insert into Course (title) values ('suspendisse potenti');
insert into Course (title) values ('praesent blandit nam');
insert into Course (title) values ('cras pellentesque');
insert into Course (title) values ('pretium quis lectus');
insert into Course (title) values ('et ultrices posuere cubilia curae');
insert into Course (title) values ('aliquam lacus morbi quis tortor');
insert into Course (title) values ('mauris lacinia sapien quis');
insert into Course (title) values ('erat tortor sollicitudin mi');
insert into Course (title) values ('tristique tortor');
insert into Course (title) values ('morbi odio odio elementum eu');
insert into Course (title) values ('nulla ultrices aliquet');
insert into Course (title) values ('volutpat erat quisque');
insert into Course (title) values ('orci luctus et ultrices');
insert into Course (title) values ('ut massa volutpat convallis');
insert into Course (title) values ('vestibulum sit amet cursus');
insert into Course (title) values ('justo in hac');
insert into Course (title) values ('dui proin');
insert into Course (title) values ('pede justo');
insert into Course (title) values ('donec pharetra magna vestibulum');
insert into Course (title) values ('platea dictumst morbi');
insert into Course (title) values ('tristique fusce congue');
insert into Course (title) values ('lectus vestibulum');
insert into Course (title) values ('id turpis integer aliquet massa');
insert into Course (title) values ('suscipit a feugiat et eros');
insert into Course (title) values ('eleifend luctus ultricies eu');
insert into Course (title) values ('augue a suscipit nulla');
insert into Course (title) values ('pellentesque quisque porta');
insert into Course (title) values ('eget massa tempor convallis');
insert into Course (title) values ('non lectus aliquam sit');
insert into Course (title) values ('praesent blandit lacinia erat');
insert into Course (title) values ('aliquam erat volutpat in');
insert into Course (title) values ('libero convallis');
insert into Course (title) values ('consequat in consequat ut');
insert into Course (title) values ('vel nisl duis ac');
insert into Course (title) values ('sapien non mi integer');
insert into Course (title) values ('magnis dis parturient');
insert into Course (title) values ('elementum nullam');
insert into Course (title) values ('nibh quisque');
insert into Course (title) values ('sodales sed');
insert into Course (title) values ('convallis tortor risus dapibus augue');
insert into Course (title) values ('luctus tincidunt nulla mollis molestie');
insert into Course (title) values ('tellus semper');
insert into Course (title) values ('sapien cursus vestibulum proin');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('sit amet');
insert into Course (title) values ('mauris laoreet ut');
insert into Course (title) values ('nisl aenean');
insert into Course (title) values ('vel lectus in');
insert into Course (title) values ('natoque penatibus et magnis dis');
insert into Course (title) values ('justo lacinia eget');
insert into Course (title) values ('posuere cubilia curae mauris');
insert into Course (title) values ('odio consequat varius integer ac');
insert into Course (title) values ('eu tincidunt');
insert into Course (title) values ('nunc viverra dapibus');
insert into Course (title) values ('imperdiet nullam orci');
insert into Course (title) values ('ut volutpat sapien arcu');
insert into Course (title) values ('odio elementum eu interdum');
insert into Course (title) values ('quisque arcu libero');
insert into Course (title) values ('odio consequat');
insert into Course (title) values ('sit amet turpis elementum ligula');
insert into Course (title) values ('ut at dolor quis odio');
insert into Course (title) values ('curabitur at ipsum ac tellus');
insert into Course (title) values ('fusce posuere felis sed lacus');
insert into Course (title) values ('mattis egestas metus aenean');
insert into Course (title) values ('vel enim sit');
insert into Course (title) values ('ultrices phasellus id');
insert into Course (title) values ('at ipsum ac tellus semper');
insert into Course (title) values ('eget eleifend luctus');
insert into Course (title) values ('donec vitae nisi');
insert into Course (title) values ('viverra diam vitae quam');
insert into Course (title) values ('cursus urna ut tellus');
insert into Course (title) values ('vitae nisi nam');
insert into Course (title) values ('arcu sed');
insert into Course (title) values ('primis in faucibus');
insert into Course (title) values ('iaculis diam erat');
insert into Course (title) values ('donec dapibus duis at velit');
insert into Course (title) values ('egestas metus');
insert into Course (title) values ('turpis adipiscing lorem vitae');
insert into Course (title) values ('eget tempus');
insert into Course (title) values ('diam vitae quam suspendisse potenti');
insert into Course (title) values ('parturient montes nascetur ridiculus mus');
insert into Course (title) values ('tellus semper');
insert into Course (title) values ('nullam porttitor');
insert into Course (title) values ('dapibus dolor');
insert into Course (title) values ('ornare imperdiet');
insert into Course (title) values ('at turpis a');
insert into Course (title) values ('vestibulum ante ipsum primis');
insert into Course (title) values ('in hac habitasse');
insert into Course (title) values ('vulputate luctus');
insert into Course (title) values ('sapien a libero nam dui');
insert into Course (title) values ('donec vitae nisi nam');
insert into Course (title) values ('dui vel nisl');
insert into Course (title) values ('ac est');
insert into Course (title) values ('arcu sed');
insert into Course (title) values ('pulvinar nulla pede ullamcorper augue');
insert into Course (title) values ('non velit donec diam');
insert into Course (title) values ('ornare imperdiet sapien');
insert into Course (title) values ('massa quis augue');
insert into Course (title) values ('vitae consectetuer eget rutrum');
insert into Course (title) values ('suspendisse potenti cras');
insert into Course (title) values ('blandit mi in porttitor');
insert into Course (title) values ('donec dapibus');
insert into Course (title) values ('mi nulla ac enim in');
insert into Course (title) values ('dictumst aliquam augue quam sollicitudin');
insert into Course (title) values ('nulla elit ac');
insert into Course (title) values ('libero nam dui proin');
insert into Course (title) values ('odio in hac habitasse');
insert into Course (title) values ('ligula vehicula consequat morbi a');
insert into Course (title) values ('non mattis');
insert into Course (title) values ('tristique in');
insert into Course (title) values ('bibendum imperdiet nullam');
insert into Course (title) values ('eget massa');
insert into Course (title) values ('luctus et');
insert into Course (title) values ('auctor gravida');
insert into Course (title) values ('at lorem integer tincidunt ante');
insert into Course (title) values ('in quam fringilla');
insert into Course (title) values ('mattis pulvinar');
insert into Course (title) values ('scelerisque mauris sit amet');
insert into Course (title) values ('sem mauris laoreet ut');
insert into Course (title) values ('tristique tortor');
insert into Course (title) values ('tristique tortor eu');
insert into Course (title) values ('eget eros');
insert into Course (title) values ('cras pellentesque volutpat');
insert into Course (title) values ('egestas metus aenean');
insert into Course (title) values ('justo pellentesque');
insert into Course (title) values ('magnis dis parturient');
insert into Course (title) values ('rhoncus aliquam lacus morbi');
insert into Course (title) values ('justo nec condimentum neque sapien');
insert into Course (title) values ('justo maecenas rhoncus aliquam');
insert into Course (title) values ('non mauris');
insert into Course (title) values ('erat eros viverra eget congue');
insert into Course (title) values ('quisque arcu libero rutrum ac');
insert into Course (title) values ('diam neque vestibulum eget');
insert into Course (title) values ('porttitor lorem id ligula suspendisse');
insert into Course (title) values ('nunc nisl duis bibendum felis');
insert into Course (title) values ('pharetra magna ac consequat metus');
insert into Course (title) values ('vestibulum sagittis');
insert into Course (title) values ('integer a');
insert into Course (title) values ('odio condimentum id luctus');
insert into Course (title) values ('pellentesque ultrices mattis odio');
insert into Course (title) values ('odio consequat varius integer ac');
insert into Course (title) values ('erat fermentum justo');
insert into Course (title) values ('lorem quisque ut');
insert into Course (title) values ('sem sed sagittis nam congue');
insert into Course (title) values ('nunc rhoncus dui vel');
insert into Course (title) values ('donec posuere metus vitae ipsum');
insert into Course (title) values ('fusce lacus');
insert into Course (title) values ('sit amet nunc');
insert into Course (title) values ('ligula pellentesque ultrices phasellus id');
insert into Course (title) values ('elit sodales scelerisque mauris');
insert into Course (title) values ('placerat ante nulla justo aliquam');
insert into Course (title) values ('nisi vulputate nonummy maecenas');
insert into Course (title) values ('in consequat ut');
insert into Course (title) values ('arcu libero rutrum ac lobortis');
insert into Course (title) values ('morbi non quam');
insert into Course (title) values ('erat nulla tempus vivamus in');
insert into Course (title) values ('id mauris vulputate elementum');
insert into Course (title) values ('duis bibendum felis sed');
insert into Course (title) values ('mi integer ac');
insert into Course (title) values ('pellentesque at nulla suspendisse potenti');
insert into Course (title) values ('mi sit amet');
insert into Course (title) values ('vitae mattis nibh ligula nec');
insert into Course (title) values ('duis at velit eu');
insert into Course (title) values ('orci luctus');
insert into Course (title) values ('venenatis turpis enim');
insert into Course (title) values ('nulla pede ullamcorper augue a');
insert into Course (title) values ('eleifend pede libero');
insert into Course (title) values ('laoreet ut rhoncus aliquet');
insert into Course (title) values ('platea dictumst etiam');
insert into Course (title) values ('quis justo maecenas');
insert into Course (title) values ('sapien dignissim vestibulum');
insert into Course (title) values ('amet nunc viverra dapibus nulla');
insert into Course (title) values ('varius integer ac leo pellentesque');
insert into Course (title) values ('erat eros');
insert into Course (title) values ('imperdiet sapien');
insert into Course (title) values ('iaculis diam erat fermentum');
insert into Course (title) values ('ullamcorper purus sit amet nulla');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('justo sit amet sapien dignissim');
insert into Course (title) values ('massa id nisl venenatis lacinia');
insert into Course (title) values ('at diam nam tristique');
insert into Course (title) values ('praesent blandit lacinia');
insert into Course (title) values ('eleifend pede libero quis orci');
insert into Course (title) values ('vulputate elementum nullam varius nulla');
insert into Course (title) values ('vel ipsum praesent');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('in porttitor pede justo');
insert into Course (title) values ('et ultrices posuere cubilia');
insert into Course (title) values ('amet eros suspendisse accumsan');
insert into Course (title) values ('ligula in lacus curabitur');
insert into Course (title) values ('faucibus orci luctus et');
insert into Course (title) values ('nulla justo aliquam quis');
insert into Course (title) values ('dictumst maecenas ut massa quis');
insert into Course (title) values ('tincidunt lacus at velit');
insert into Course (title) values ('pede malesuada');
insert into Course (title) values ('bibendum morbi non quam nec');
insert into Course (title) values ('id turpis');
insert into Course (title) values ('lobortis ligula sit');
insert into Course (title) values ('neque vestibulum eget');
insert into Course (title) values ('felis donec semper sapien a');
insert into Course (title) values ('suscipit a feugiat et eros');
insert into Course (title) values ('ridiculus mus etiam');
insert into Course (title) values ('rhoncus aliquam lacus morbi quis');
insert into Course (title) values ('quis libero nullam');
insert into Course (title) values ('augue aliquam');
insert into Course (title) values ('at turpis donec posuere metus');
insert into Course (title) values ('rutrum nulla tellus in');
insert into Course (title) values ('maecenas leo odio condimentum id');
insert into Course (title) values ('massa tempor convallis nulla neque');
insert into Course (title) values ('in eleifend quam a');
insert into Course (title) values ('nisl ut volutpat sapien');
insert into Course (title) values ('cubilia curae');
insert into Course (title) values ('risus auctor sed tristique');
insert into Course (title) values ('vel dapibus at');
insert into Course (title) values ('diam in magna bibendum imperdiet');
insert into Course (title) values ('vestibulum sagittis sapien cum sociis');
insert into Course (title) values ('lacus morbi quis');
insert into Course (title) values ('diam neque');
insert into Course (title) values ('pellentesque quisque porta');
insert into Course (title) values ('suscipit ligula in');
insert into Course (title) values ('cursus id turpis');
insert into Course (title) values ('hac habitasse');
insert into Course (title) values ('pede posuere');
insert into Course (title) values ('vulputate vitae');
insert into Course (title) values ('morbi odio odio elementum');
insert into Course (title) values ('interdum mauris ullamcorper');
insert into Course (title) values ('dui vel sem sed');
insert into Course (title) values ('curae donec pharetra magna');
insert into Course (title) values ('justo in');
insert into Course (title) values ('integer ac leo pellentesque');
insert into Course (title) values ('ac lobortis');
insert into Course (title) values ('libero nullam sit');
insert into Course (title) values ('ultrices phasellus id sapien in');
insert into Course (title) values ('leo odio condimentum');
insert into Course (title) values ('dui vel sem sed sagittis');
insert into Course (title) values ('massa quis');
insert into Course (title) values ('parturient montes nascetur ridiculus');
insert into Course (title) values ('dictumst maecenas ut');
insert into Course (title) values ('ligula sit amet');
insert into Course (title) values ('placerat ante nulla justo aliquam');
insert into Course (title) values ('sed tristique in tempus');
insert into Course (title) values ('potenti cras in purus eu');
insert into Course (title) values ('quisque arcu libero rutrum ac');
insert into Course (title) values ('sed nisl nunc rhoncus');
insert into Course (title) values ('etiam pretium iaculis justo in');
insert into Course (title) values ('tincidunt eget');
insert into Course (title) values ('nulla facilisi cras non velit');
insert into Course (title) values ('nulla suscipit ligula');
insert into Course (title) values ('sed magna at nunc');
insert into Course (title) values ('felis ut at dolor quis');
insert into Course (title) values ('eget eleifend luctus');
insert into Course (title) values ('pede posuere nonummy');
insert into Course (title) values ('lobortis sapien sapien');
insert into Course (title) values ('cubilia curae donec');
insert into Course (title) values ('ornare imperdiet sapien urna');
insert into Course (title) values ('fringilla rhoncus mauris enim');
insert into Course (title) values ('sit amet');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('nisi venenatis tristique fusce');
insert into Course (title) values ('est quam pharetra magna ac');
insert into Course (title) values ('id massa id');
insert into Course (title) values ('pellentesque quisque porta volutpat');
insert into Course (title) values ('donec quis orci eget');
insert into Course (title) values ('nulla ut erat');
insert into Course (title) values ('amet justo');
insert into Course (title) values ('rhoncus mauris enim');
insert into Course (title) values ('phasellus in felis donec semper');
insert into Course (title) values ('nulla nisl nunc nisl duis');
insert into Course (title) values ('nisi venenatis tristique');
insert into Course (title) values ('imperdiet et commodo vulputate');
insert into Course (title) values ('nibh in lectus');
insert into Course (title) values ('suscipit nulla elit');
insert into Course (title) values ('nisl venenatis');
insert into Course (title) values ('consectetuer adipiscing elit proin');
insert into Course_Material (url, course_id) values ('https://harvard.edu/proin/at/turpis/a.js?ellus', 2);
insert into Course_Material (url, course_id) values ('http://hatena.ne.jp/at/vulputate/vitae.html?justo=fermentus&vulputate=tuaenean', 2);
insert into Course_Material (url, course_id) values ('https://ning.com/sed.xml?eu=potet', 4);
insert into Course_Material (url, course_id) values ('http://simplemachines.org/ipsum/dolor/sit.html?amn&duis=mattis', 5);
insert into Course_Material (url, course_id) values ('http://unblog.fr/ac/enim/in/tempor.js?felis=id&uue=auitae=eu&nisi=orci', 6);
insert into Course_Material (url) values ('http://time.com/nisl/ut/volutpat/sapien/arcu.jpg?eu');
insert into Course_Material (url) values ('http://senate.gov/potenti/nullam/porttitor/lacus.jsp?sagittis=enim');
insert into Course_Material (url) values ('http://scientificamerican.com/sed/tincidunt/eu/felis/fusce/posuere/felis.js?venenatis=a&lacinia=nibh&aenean=in');
insert into Course_Material (url) values ('https://ameblo.jp/augue/vel.aspx?in=in&hac=congue&habitasse=eti');
insert into Course_Material (url) values ('https://t-online.de/auctor/gravida/sem/praesent');
