insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('interdum in ante');
insert into Course (title) values ('vel pede');
insert into Course (title) values ('turpis integer aliquet massa');
insert into Course (title) values ('turpis adipiscing lorem vitae mattis');
insert into Course (title) values ('suscipit a feugiat');
insert into Course (title) values ('malesuada in');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('nisi eu orci mauris lacinia');
insert into Course (title) values ('phasellus id sapien');
insert into Course (title) values ('aliquet massa id lobortis convallis');
insert into Course (title) values ('ac nibh');
insert into Course (title) values ('dolor morbi');
insert into Course (title) values ('consectetuer eget');
insert into Course (title) values ('nulla tempus vivamus');
insert into Course (title) values ('mauris eget massa');
insert into Course (title) values ('tortor duis mattis egestas metus');
insert into Course (title) values ('dictumst etiam faucibus cursus urna');
insert into Course (title) values ('ultrices mattis odio donec vitae');
insert into Course (title) values ('in magna bibendum');
insert into Course (title) values ('nulla sed vel');
insert into Course (title) values ('turpis sed ante vivamus tortor');
insert into Course (title) values ('at turpis a pede posuere');
insert into Course (title) values ('libero nullam sit');
insert into Course (title) values ('scelerisque quam');
insert into Course (title) values ('lorem ipsum dolor sit amet');
insert into Course (title) values ('in faucibus orci luctus');
insert into Course (title) values ('massa tempor convallis');
insert into Course (title) values ('sit amet justo morbi ut');
insert into Course (title) values ('tempus semper');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('duis bibendum morbi');
insert into Course (title) values ('nisi venenatis tristique fusce');
insert into Course (title) values ('lacus morbi sem mauris laoreet');
insert into Course (title) values ('magna at nunc commodo placerat');
insert into Course (title) values ('congue eget');
insert into Course (title) values ('hac habitasse platea dictumst');
insert into Course (title) values ('semper rutrum');
insert into Course (title) values ('etiam pretium iaculis justo in');
insert into Course (title) values ('a ipsum integer a nibh');
insert into Course (title) values ('vulputate nonummy maecenas');
insert into Course (title) values ('duis consequat dui nec nisi');
insert into Course (title) values ('risus praesent');
insert into Course (title) values ('justo eu massa donec');
insert into Course (title) values ('integer a nibh in quis');
insert into Course (title) values ('curabitur at ipsum ac');
insert into Course (title) values ('sapien ut nunc vestibulum ante');
insert into Course (title) values ('amet consectetuer adipiscing');
insert into Course (title) values ('odio curabitur convallis');
insert into Course (title) values ('ac consequat metus sapien ut');
insert into Course (title) values ('a odio in');
insert into Course (title) values ('porttitor id consequat');
insert into Course (title) values ('est congue elementum');
insert into Course (title) values ('ornare consequat lectus');
insert into Course (title) values ('nulla neque libero');
insert into Course (title) values ('nunc purus phasellus');
insert into Course (title) values ('quisque ut erat curabitur gravida');
insert into Course (title) values ('neque aenean');
insert into Course (title) values ('orci vehicula condimentum curabitur in');
insert into Course (title) values ('id massa id');
insert into Course (title) values ('justo in');
insert into Course (title) values ('aliquet pulvinar sed nisl nunc');
insert into Course (title) values ('condimentum curabitur in');
insert into Course (title) values ('vulputate ut');
insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('dis parturient montes nascetur ridiculus');
insert into Course (title) values ('vel est donec odio');
insert into Course (title) values ('in felis eu sapien');
insert into Course (title) values ('nunc nisl duis');
insert into Course (title) values ('consectetuer adipiscing elit proin interdum');
insert into Course (title) values ('primis in faucibus');
insert into Course (title) values ('potenti in eleifend');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('diam nam tristique tortor eu');
insert into Course (title) values ('suspendisse potenti');
insert into Course (title) values ('ante ipsum primis in faucibus');
insert into Course (title) values ('nibh ligula nec sem duis');
insert into Course (title) values ('ut volutpat');
insert into Course (title) values ('sagittis sapien cum sociis natoque');
insert into Course (title) values ('iaculis diam');
insert into Course (title) values ('ante ipsum primis in faucibus');
insert into Course (title) values ('aliquam convallis nunc');
insert into Course (title) values ('erat eros viverra eget');
insert into Course (title) values ('congue elementum in hac habitasse');
insert into Course (title) values ('vel accumsan tellus nisi');
insert into Course (title) values ('nulla tellus');
insert into Course (title) values ('cras in');
insert into Course (title) values ('in sapien');
insert into Course (title) values ('dictumst aliquam augue quam sollicitudin');
insert into Course (title) values ('lobortis convallis');
insert into Course (title) values ('ante vestibulum');
insert into Course (title) values ('integer a nibh');
insert into Course (title) values ('mi nulla');
insert into Course (title) values ('dapibus augue vel');
insert into Course (title) values ('sed tristique in tempus');
insert into Course (title) values ('donec ut mauris eget');
insert into Course (title) values ('turpis nec euismod scelerisque quam');
insert into Course (title) values ('sed lacus morbi sem');
insert into Course (title) values ('et ultrices');
insert into Course (title) values ('proin risus praesent');
insert into Course (title) values ('lacus morbi');
insert into Course (title) values ('ultrices erat tortor sollicitudin');
insert into Course (title) values ('curae nulla dapibus dolor');
insert into Course (title) values ('integer pede');
insert into Course (title) values ('ridiculus mus vivamus vestibulum');
insert into Course (title) values ('ipsum aliquam non');
insert into Course (title) values ('suscipit a feugiat et');
insert into Course (title) values ('cursus urna');
insert into Course (title) values ('tincidunt in leo maecenas pulvinar');
insert into Course (title) values ('amet eros');
insert into Course (title) values ('mauris ullamcorper purus');
insert into Course (title) values ('vel augue vestibulum');
insert into Course (title) values ('ultrices posuere cubilia');
insert into Course (title) values ('nullam varius nulla facilisi');
insert into Course (title) values ('velit eu');
insert into Course (title) values ('nam ultrices libero non');
insert into Course (title) values ('nisi at nibh');
insert into Course (title) values ('ipsum dolor');
insert into Course (title) values ('ultrices posuere cubilia');
insert into Course (title) values ('ipsum ac');
insert into Course (title) values ('ipsum primis in');
insert into Course (title) values ('montes nascetur');
insert into Course (title) values ('justo in hac habitasse');
insert into Course (title) values ('orci pede venenatis non');
insert into Course (title) values ('libero nullam sit amet turpis');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('nulla dapibus');
insert into Course (title) values ('rhoncus dui vel sem sed');
insert into Course (title) values ('sagittis nam congue risus semper');
insert into Course (title) values ('justo nec condimentum neque sapien');
insert into Course (title) values ('ipsum integer a nibh in');
insert into Course (title) values ('donec dapibus duis at velit');
insert into Course (title) values ('neque libero');
insert into Course (title) values ('sed vestibulum sit amet cursus');
insert into Course (title) values ('sagittis dui vel');
insert into Course (title) values ('ut odio cras mi');
insert into Course (title) values ('aliquam erat volutpat in');
insert into Course (title) values ('est donec odio justo sollicitudin');
insert into Course (title) values ('in faucibus');
insert into Course (title) values ('consequat lectus');
insert into Course (title) values ('risus semper porta');
insert into Course (title) values ('lorem ipsum dolor sit');
insert into Course (title) values ('nam congue risus semper porta');
insert into Course (title) values ('ipsum aliquam non mauris');
insert into Course (title) values ('dapibus duis at velit eu');
insert into Course (title) values ('ipsum dolor sit amet consectetuer');
insert into Course (title) values ('diam nam tristique');
insert into Course (title) values ('aliquet pulvinar');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('ultricies eu');
insert into Course (title) values ('nec nisi volutpat eleifend donec');
insert into Course (title) values ('hac habitasse');
insert into Course (title) values ('vel pede morbi porttitor lorem');
insert into Course (title) values ('elit proin interdum mauris non');
insert into Course (title) values ('et magnis dis parturient montes');
insert into Course (title) values ('nisi vulputate nonummy');
insert into Course (title) values ('orci luctus');
insert into Course (title) values ('varius integer ac leo pellentesque');
insert into Course (title) values ('in lacus curabitur');
insert into Course (title) values ('consectetuer eget rutrum at');
insert into Course (title) values ('augue luctus');
insert into Course (title) values ('risus dapibus augue vel');
insert into Course (title) values ('rhoncus sed vestibulum');
insert into Course (title) values ('justo sit');
insert into Course (title) values ('nulla nisl nunc nisl');
insert into Course (title) values ('vestibulum ante ipsum primis in');
insert into Course (title) values ('montes nascetur');
insert into Course (title) values ('vestibulum ante');
insert into Course (title) values ('massa quis');
insert into Course (title) values ('cursus id turpis integer');
insert into Course (title) values ('ac tellus semper interdum mauris');
insert into Course (title) values ('magna vestibulum aliquet ultrices');
insert into Course (title) values ('aenean auctor gravida sem praesent');
insert into Course (title) values ('ultrices posuere cubilia curae');
insert into Course (title) values ('tortor id nulla ultrices aliquet');
insert into Course (title) values ('justo maecenas rhoncus');
insert into Course (title) values ('ac nulla sed vel enim');
insert into Course (title) values ('aliquet massa id');
insert into Course (title) values ('augue vestibulum ante ipsum');
insert into Course (title) values ('ultrices posuere cubilia curae mauris');
insert into Course (title) values ('est et tempus semper');
insert into Course (title) values ('adipiscing lorem vitae mattis');
insert into Course (title) values ('tempus semper');
insert into Course (title) values ('ligula nec sem duis');
insert into Course (title) values ('ut at dolor');
insert into Course (title) values ('a pede posuere');
insert into Course (title) values ('id ornare imperdiet');
insert into Course (title) values ('lacinia nisi');
insert into Course (title) values ('dapibus duis');
insert into Course (title) values ('proin eu mi');
insert into Course (title) values ('sapien dignissim vestibulum vestibulum');
insert into Course (title) values ('vel pede');
insert into Course (title) values ('elementum pellentesque');
insert into Course (title) values ('nisi vulputate');
insert into Course (title) values ('vulputate vitae nisl aenean lectus');
insert into Course (title) values ('eget semper');
insert into Course (title) values ('mattis egestas metus aenean');
insert into Course (title) values ('faucibus orci luctus et ultrices');
insert into Course (title) values ('amet eros suspendisse accumsan tortor');
insert into Course (title) values ('in porttitor');
insert into Course (title) values ('bibendum imperdiet');
insert into Course (title) values ('et ultrices posuere cubilia');
insert into Course (title) values ('sollicitudin vitae consectetuer eget');
insert into Course (title) values ('augue vestibulum rutrum rutrum');
insert into Course (title) values ('ut nunc');
insert into Course (title) values ('elementum in hac habitasse platea');
insert into Course (title) values ('nulla neque');
insert into Course (title) values ('turpis enim blandit mi in');
insert into Course (title) values ('vivamus vestibulum sagittis');
insert into Course (title) values ('sodales scelerisque');
insert into Course (title) values ('nullam porttitor lacus');
insert into Course (title) values ('ut erat curabitur');
insert into Course (title) values ('amet sapien');
insert into Course (title) values ('sed vestibulum sit');
insert into Course (title) values ('in hac habitasse platea dictumst');
insert into Course (title) values ('morbi non lectus aliquam sit');
insert into Course (title) values ('lectus aliquam sit');
insert into Course (title) values ('sapien cursus vestibulum proin eu');
insert into Course (title) values ('nulla justo');
insert into Course (title) values ('libero rutrum ac');
insert into Course (title) values ('mauris non');
insert into Course (title) values ('et ultrices posuere cubilia curae');
insert into Course (title) values ('aliquam augue quam sollicitudin vitae');
insert into Course (title) values ('nisl nunc rhoncus');
insert into Course (title) values ('purus aliquet at feugiat');
insert into Course (title) values ('ligula nec sem duis aliquam');
insert into Course (title) values ('ac est lacinia nisi venenatis');
insert into Course (title) values ('elit ac');
insert into Course (title) values ('quis turpis eget elit');
insert into Course (title) values ('justo sollicitudin ut');
insert into Course (title) values ('nonummy integer non velit');
insert into Course (title) values ('justo in');
insert into Course (title) values ('nullam varius nulla facilisi');
insert into Course (title) values ('pellentesque ultrices phasellus');
insert into Course (title) values ('interdum mauris non ligula pellentesque');
insert into Course (title) values ('adipiscing elit');
insert into Course (title) values ('porta volutpat quam pede lobortis');
insert into Course (title) values ('amet lobortis');
insert into Course (title) values ('morbi porttitor lorem id ligula');
insert into Course (title) values ('in faucibus orci');
insert into Course (title) values ('vestibulum eget vulputate');
insert into Course (title) values ('blandit nam nulla integer pede');
insert into Course (title) values ('parturient montes nascetur');
insert into Course (title) values ('faucibus orci luctus et');
insert into Course (title) values ('arcu libero');
insert into Course (title) values ('integer pede justo lacinia');
insert into Course (title) values ('vestibulum ante ipsum primis in');
insert into Course (title) values ('ultrices erat tortor sollicitudin');
insert into Course (title) values ('integer pede justo');
insert into Course (title) values ('eget orci vehicula condimentum curabitur');
insert into Course (title) values ('nulla eget');
insert into Course (title) values ('quisque erat eros');
insert into Course (title) values ('eget tempus');
insert into Course (title) values ('integer tincidunt');
insert into Course (title) values ('maecenas leo');
insert into Course (title) values ('cursus id turpis');
insert into Course (title) values ('nulla eget eros elementum');
insert into Course (title) values ('at velit vivamus vel nulla');
insert into Course (title) values ('suspendisse ornare consequat');
insert into Course (title) values ('odio porttitor id');
insert into Course (title) values ('lobortis vel dapibus');
insert into Course (title) values ('hendrerit at');
insert into Course (title) values ('molestie nibh');
insert into Course (title) values ('ac leo pellentesque');
insert into Course (title) values ('nulla tempus');
insert into Course (title) values ('justo in');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('in hac');
insert into Course (title) values ('donec pharetra magna vestibulum aliquet');
insert into Course (title) values ('nulla mollis molestie');
insert into Course (title) values ('magna vulputate luctus cum');
insert into Course (title) values ('eros elementum pellentesque quisque porta');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('lectus vestibulum');
insert into Course (title) values ('velit vivamus vel nulla eget');
insert into Course (title) values ('lectus pellentesque at nulla');
insert into Course (title) values ('sit amet eleifend pede libero');
insert into Course (title) values ('lectus suspendisse');
insert into Course (title) values ('sociis natoque penatibus');
insert into Course (title) values ('in felis eu');
insert into Course (title) values ('aenean lectus pellentesque eget nunc');
insert into Course (title) values ('morbi quis tortor id nulla');
insert into Course (title) values ('diam in magna bibendum');
insert into Course (title) values ('blandit ultrices');
insert into Course (title) values ('justo in blandit ultrices');
insert into Course (title) values ('euismod scelerisque quam turpis');
insert into Course (title) values ('natoque penatibus et magnis');
insert into Course (title) values ('mus etiam vel');
insert into Course (title) values ('aenean auctor');
insert into Course (title) values ('ante ipsum primis');
insert into Course (title) values ('felis eu');
insert into Course (title) values ('vitae ipsum aliquam non mauris');
insert into Course (title) values ('at turpis donec posuere');
insert into Course (title) values ('ultrices libero');
insert into Course (title) values ('ut nulla');
insert into Course (title) values ('morbi vel');
insert into Course (title) values ('euismod scelerisque quam');
insert into Course (title) values ('iaculis justo');
insert into Course (title) values ('ut massa');
insert into Course (title) values ('ultrices libero non mattis');
insert into Course (title) values ('amet consectetuer adipiscing elit');
insert into Course (title) values ('dui proin leo odio porttitor');
insert into Course (title) values ('libero convallis eget eleifend');
insert into Course (title) values ('diam erat fermentum justo');
insert into Course (title) values ('pellentesque eget nunc');
insert into Course (title) values ('nulla ac enim');
insert into Course (title) values ('parturient montes nascetur ridiculus');
insert into Course (title) values ('suspendisse potenti');
insert into Course (title) values ('praesent blandit nam');
insert into Course (title) values ('cras pellentesque');
insert into Course (title) values ('pretium quis lectus');
insert into Course (title) values ('et ultrices posuere cubilia curae');
insert into Course (title) values ('aliquam lacus morbi quis tortor');
insert into Course (title) values ('mauris lacinia sapien quis');
insert into Course (title) values ('erat tortor sollicitudin mi');
insert into Course (title) values ('tristique tortor');
insert into Course (title) values ('morbi odio odio elementum eu');
insert into Course (title) values ('nulla ultrices aliquet');
insert into Course (title) values ('volutpat erat quisque');
insert into Course (title) values ('orci luctus et ultrices');
insert into Course (title) values ('ut massa volutpat convallis');
insert into Course (title) values ('vestibulum sit amet cursus');
insert into Course (title) values ('justo in hac');
insert into Course (title) values ('dui proin');
insert into Course (title) values ('pede justo');
insert into Course (title) values ('donec pharetra magna vestibulum');
insert into Course (title) values ('platea dictumst morbi');
insert into Course (title) values ('tristique fusce congue');
insert into Course (title) values ('lectus vestibulum');
insert into Course (title) values ('id turpis integer aliquet massa');
insert into Course (title) values ('suscipit a feugiat et eros');
insert into Course (title) values ('eleifend luctus ultricies eu');
insert into Course (title) values ('augue a suscipit nulla');
insert into Course (title) values ('pellentesque quisque porta');
insert into Course (title) values ('eget massa tempor convallis');
insert into Course (title) values ('non lectus aliquam sit');
insert into Course (title) values ('praesent blandit lacinia erat');
insert into Course (title) values ('aliquam erat volutpat in');
insert into Course (title) values ('libero convallis');
insert into Course (title) values ('consequat in consequat ut');
insert into Course (title) values ('vel nisl duis ac');
insert into Course (title) values ('sapien non mi integer');
insert into Course (title) values ('magnis dis parturient');
insert into Course (title) values ('elementum nullam');
insert into Course (title) values ('nibh quisque');
insert into Course (title) values ('sodales sed');
insert into Course (title) values ('convallis tortor risus dapibus augue');
insert into Course (title) values ('luctus tincidunt nulla mollis molestie');
insert into Course (title) values ('tellus semper');
insert into Course (title) values ('sapien cursus vestibulum proin');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('sit amet');
insert into Course (title) values ('mauris laoreet ut');
insert into Course (title) values ('nisl aenean');
insert into Course (title) values ('vel lectus in');
insert into Course (title) values ('natoque penatibus et magnis dis');
insert into Course (title) values ('justo lacinia eget');
insert into Course (title) values ('posuere cubilia curae mauris');
insert into Course (title) values ('odio consequat varius integer ac');
insert into Course (title) values ('eu tincidunt');
insert into Course (title) values ('nunc viverra dapibus');
insert into Course (title) values ('imperdiet nullam orci');
insert into Course (title) values ('ut volutpat sapien arcu');
insert into Course (title) values ('odio elementum eu interdum');
insert into Course (title) values ('quisque arcu libero');
insert into Course (title) values ('odio consequat');
insert into Course (title) values ('sit amet turpis elementum ligula');
insert into Course (title) values ('ut at dolor quis odio');
insert into Course (title) values ('curabitur at ipsum ac tellus');
insert into Course (title) values ('fusce posuere felis sed lacus');
insert into Course (title) values ('mattis egestas metus aenean');
insert into Course (title) values ('vel enim sit');
insert into Course (title) values ('ultrices phasellus id');
insert into Course (title) values ('at ipsum ac tellus semper');
insert into Course (title) values ('eget eleifend luctus');
insert into Course (title) values ('donec vitae nisi');
insert into Course (title) values ('viverra diam vitae quam');
insert into Course (title) values ('cursus urna ut tellus');
insert into Course (title) values ('vitae nisi nam');
insert into Course (title) values ('arcu sed');
insert into Course (title) values ('primis in faucibus');
insert into Course (title) values ('iaculis diam erat');
insert into Course (title) values ('donec dapibus duis at velit');
insert into Course (title) values ('egestas metus');
insert into Course (title) values ('turpis adipiscing lorem vitae');
insert into Course (title) values ('eget tempus');
insert into Course (title) values ('diam vitae quam suspendisse potenti');
insert into Course (title) values ('parturient montes nascetur ridiculus mus');
insert into Course (title) values ('tellus semper');
insert into Course (title) values ('nullam porttitor');
insert into Course (title) values ('dapibus dolor');
insert into Course (title) values ('ornare imperdiet');
insert into Course (title) values ('at turpis a');
insert into Course (title) values ('vestibulum ante ipsum primis');
insert into Course (title) values ('in hac habitasse');
insert into Course (title) values ('vulputate luctus');
insert into Course (title) values ('sapien a libero nam dui');
insert into Course (title) values ('donec vitae nisi nam');
insert into Course (title) values ('dui vel nisl');
insert into Course (title) values ('ac est');
insert into Course (title) values ('arcu sed');
insert into Course (title) values ('pulvinar nulla pede ullamcorper augue');
insert into Course (title) values ('non velit donec diam');
insert into Course (title) values ('ornare imperdiet sapien');
insert into Course (title) values ('massa quis augue');
insert into Course (title) values ('vitae consectetuer eget rutrum');
insert into Course (title) values ('suspendisse potenti cras');
insert into Course (title) values ('blandit mi in porttitor');
insert into Course (title) values ('donec dapibus');
insert into Course (title) values ('mi nulla ac enim in');
insert into Course (title) values ('dictumst aliquam augue quam sollicitudin');
insert into Course (title) values ('nulla elit ac');
insert into Course (title) values ('libero nam dui proin');
insert into Course (title) values ('odio in hac habitasse');
insert into Course (title) values ('ligula vehicula consequat morbi a');
insert into Course (title) values ('non mattis');
insert into Course (title) values ('tristique in');
insert into Course (title) values ('bibendum imperdiet nullam');
insert into Course (title) values ('eget massa');
insert into Course (title) values ('luctus et');
insert into Course (title) values ('auctor gravida');
insert into Course (title) values ('at lorem integer tincidunt ante');
insert into Course (title) values ('in quam fringilla');
insert into Course (title) values ('mattis pulvinar');
insert into Course (title) values ('scelerisque mauris sit amet');
insert into Course (title) values ('sem mauris laoreet ut');
insert into Course (title) values ('tristique tortor');
insert into Course (title) values ('tristique tortor eu');
insert into Course (title) values ('eget eros');
insert into Course (title) values ('cras pellentesque volutpat');
insert into Course (title) values ('egestas metus aenean');
insert into Course (title) values ('justo pellentesque');
insert into Course (title) values ('magnis dis parturient');
insert into Course (title) values ('rhoncus aliquam lacus morbi');
insert into Course (title) values ('justo nec condimentum neque sapien');
insert into Course (title) values ('justo maecenas rhoncus aliquam');
insert into Course (title) values ('non mauris');
insert into Course (title) values ('erat eros viverra eget congue');
insert into Course (title) values ('quisque arcu libero rutrum ac');
insert into Course (title) values ('diam neque vestibulum eget');
insert into Course (title) values ('porttitor lorem id ligula suspendisse');
insert into Course (title) values ('nunc nisl duis bibendum felis');
insert into Course (title) values ('pharetra magna ac consequat metus');
insert into Course (title) values ('vestibulum sagittis');
insert into Course (title) values ('integer a');
insert into Course (title) values ('odio condimentum id luctus');
insert into Course (title) values ('pellentesque ultrices mattis odio');
insert into Course (title) values ('odio consequat varius integer ac');
insert into Course (title) values ('erat fermentum justo');
insert into Course (title) values ('lorem quisque ut');
insert into Course (title) values ('sem sed sagittis nam congue');
insert into Course (title) values ('nunc rhoncus dui vel');
insert into Course (title) values ('donec posuere metus vitae ipsum');
insert into Course (title) values ('fusce lacus');
insert into Course (title) values ('sit amet nunc');
insert into Course (title) values ('ligula pellentesque ultrices phasellus id');
insert into Course (title) values ('elit sodales scelerisque mauris');
insert into Course (title) values ('placerat ante nulla justo aliquam');
insert into Course (title) values ('nisi vulputate nonummy maecenas');
insert into Course (title) values ('in consequat ut');
insert into Course (title) values ('arcu libero rutrum ac lobortis');
insert into Course (title) values ('morbi non quam');
insert into Course (title) values ('erat nulla tempus vivamus in');
insert into Course (title) values ('id mauris vulputate elementum');
insert into Course (title) values ('duis bibendum felis sed');
insert into Course (title) values ('mi integer ac');
insert into Course (title) values ('pellentesque at nulla suspendisse potenti');
insert into Course (title) values ('mi sit amet');
insert into Course (title) values ('vitae mattis nibh ligula nec');
insert into Course (title) values ('duis at velit eu');
insert into Course (title) values ('orci luctus');
insert into Course (title) values ('venenatis turpis enim');
insert into Course (title) values ('nulla pede ullamcorper augue a');
insert into Course (title) values ('eleifend pede libero');
insert into Course (title) values ('laoreet ut rhoncus aliquet');
insert into Course (title) values ('platea dictumst etiam');
insert into Course (title) values ('quis justo maecenas');
insert into Course (title) values ('sapien dignissim vestibulum');
insert into Course (title) values ('amet nunc viverra dapibus nulla');
insert into Course (title) values ('varius integer ac leo pellentesque');
insert into Course (title) values ('erat eros');
insert into Course (title) values ('imperdiet sapien');
insert into Course (title) values ('iaculis diam erat fermentum');
insert into Course (title) values ('ullamcorper purus sit amet nulla');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('justo sit amet sapien dignissim');
insert into Course (title) values ('massa id nisl venenatis lacinia');
insert into Course (title) values ('at diam nam tristique');
insert into Course (title) values ('praesent blandit lacinia');
insert into Course (title) values ('eleifend pede libero quis orci');
insert into Course (title) values ('vulputate elementum nullam varius nulla');
insert into Course (title) values ('vel ipsum praesent');
insert into Course (title) values ('nisi at nibh in hac');
insert into Course (title) values ('in porttitor pede justo');
insert into Course (title) values ('et ultrices posuere cubilia');
insert into Course (title) values ('amet eros suspendisse accumsan');
insert into Course (title) values ('ligula in lacus curabitur');
insert into Course (title) values ('faucibus orci luctus et');
insert into Course (title) values ('nulla justo aliquam quis');
insert into Course (title) values ('dictumst maecenas ut massa quis');
insert into Course (title) values ('tincidunt lacus at velit');
insert into Course (title) values ('pede malesuada');
insert into Course (title) values ('bibendum morbi non quam nec');
insert into Course (title) values ('id turpis');
insert into Course (title) values ('lobortis ligula sit');
insert into Course (title) values ('neque vestibulum eget');
insert into Course (title) values ('felis donec semper sapien a');
insert into Course (title) values ('suscipit a feugiat et eros');
insert into Course (title) values ('ridiculus mus etiam');
insert into Course (title) values ('rhoncus aliquam lacus morbi quis');
insert into Course (title) values ('quis libero nullam');
insert into Course (title) values ('augue aliquam');
insert into Course (title) values ('at turpis donec posuere metus');
insert into Course (title) values ('rutrum nulla tellus in');
insert into Course (title) values ('maecenas leo odio condimentum id');
insert into Course (title) values ('massa tempor convallis nulla neque');
insert into Course (title) values ('in eleifend quam a');
insert into Course (title) values ('nisl ut volutpat sapien');
insert into Course (title) values ('cubilia curae');
insert into Course (title) values ('risus auctor sed tristique');
insert into Course (title) values ('vel dapibus at');
insert into Course (title) values ('diam in magna bibendum imperdiet');
insert into Course (title) values ('vestibulum sagittis sapien cum sociis');
insert into Course (title) values ('lacus morbi quis');
insert into Course (title) values ('diam neque');
insert into Course (title) values ('pellentesque quisque porta');
insert into Course (title) values ('suscipit ligula in');
insert into Course (title) values ('cursus id turpis');
insert into Course (title) values ('hac habitasse');
insert into Course (title) values ('pede posuere');
insert into Course (title) values ('vulputate vitae');
insert into Course (title) values ('morbi odio odio elementum');
insert into Course (title) values ('interdum mauris ullamcorper');
insert into Course (title) values ('dui vel sem sed');
insert into Course (title) values ('curae donec pharetra magna');
insert into Course (title) values ('justo in');
insert into Course (title) values ('integer ac leo pellentesque');
insert into Course (title) values ('ac lobortis');
insert into Course (title) values ('libero nullam sit');
insert into Course (title) values ('ultrices phasellus id sapien in');
insert into Course (title) values ('leo odio condimentum');
insert into Course (title) values ('dui vel sem sed sagittis');
insert into Course (title) values ('massa quis');
insert into Course (title) values ('parturient montes nascetur ridiculus');
insert into Course (title) values ('dictumst maecenas ut');
insert into Course (title) values ('ligula sit amet');
insert into Course (title) values ('placerat ante nulla justo aliquam');
insert into Course (title) values ('sed tristique in tempus');
insert into Course (title) values ('potenti cras in purus eu');
insert into Course (title) values ('quisque arcu libero rutrum ac');
insert into Course (title) values ('sed nisl nunc rhoncus');
insert into Course (title) values ('etiam pretium iaculis justo in');
insert into Course (title) values ('tincidunt eget');
insert into Course (title) values ('nulla facilisi cras non velit');
insert into Course (title) values ('nulla suscipit ligula');
insert into Course (title) values ('sed magna at nunc');
insert into Course (title) values ('felis ut at dolor quis');
insert into Course (title) values ('eget eleifend luctus');
insert into Course (title) values ('pede posuere nonummy');
insert into Course (title) values ('lobortis sapien sapien');
insert into Course (title) values ('cubilia curae donec');
insert into Course (title) values ('ornare imperdiet sapien urna');
insert into Course (title) values ('fringilla rhoncus mauris enim');
insert into Course (title) values ('sit amet');
insert into Course (title) values ('ipsum primis');
insert into Course (title) values ('nisi venenatis tristique fusce');
insert into Course (title) values ('est quam pharetra magna ac');
insert into Course (title) values ('id massa id');
insert into Course (title) values ('pellentesque quisque porta volutpat');
insert into Course (title) values ('donec quis orci eget');
insert into Course (title) values ('nulla ut erat');
insert into Course (title) values ('amet justo');
insert into Course (title) values ('rhoncus mauris enim');
insert into Course (title) values ('phasellus in felis donec semper');
insert into Course (title) values ('nulla nisl nunc nisl duis');
insert into Course (title) values ('nisi venenatis tristique');
insert into Course (title) values ('imperdiet et commodo vulputate');
insert into Course (title) values ('nibh in lectus');
insert into Course (title) values ('suscipit nulla elit');
insert into Course (title) values ('nisl venenatis');
insert into Course (title) values ('consectetuer adipiscing elit proin');
insert into Course_Material (url, course_id) values ('https://harvard.edu/proin/at/turpis/a.js?volutpat=ut&quam=erat&pede=id&lobortis=mauris&ligula=vulputate&sit=elementum&amet=nullam&eleifend=varius&pede=nulla&libero=facilisi&quis=cras&orci=non&nullam=velit&molestie=nec&nibh=nisi&in=vulputate&lectus=nonummy&pellentesque=maecenas&at=tincidunt&nulla=lacus&suspendisse=at&potenti=velit&cras=vivamus&in=vel&purus=nulla&eu=eget&magna=eros&vulputate=elementum&luctus=pellentesque&cum=quisque&sociis=porta&natoque=volutpat&penatibus=erat&et=quisque&magnis=erat&dis=eros&parturient=viverra&montes=eget&nascetur=congue&ridiculus=eget&mus=semper&vivamus=rutrum&vestibulum=nulla&sagittis=nunc&sapien=purus&cum=phasellus', 2);
insert into Course_Material (url, course_id) values ('http://hatena.ne.jp/at/vulputate/vitae.html?justo=fermentum&morbi=justo&ut=nec&odio=condimentum&cras=neque&mi=sapien&pede=placerat&malesuada=ante&in=nulla&imperdiet=justo&et=aliquam&commodo=quis&vulputate=turpis&justo=eget&in=elit&blandit=sodales&ultrices=scelerisque&enim=mauris&lorem=sit&ipsum=amet&dolor=eros&sit=suspendisse&amet=accumsan&consectetuer=tortor&adipiscing=quis&elit=turpis&proin=sed&interdum=ante&mauris=vivamus&non=tortor&ligula=duis&pellentesque=mattis&ultrices=egestas&phasellus=metus&id=aenean', 3);
insert into Course_Material (url, course_id) values ('https://ning.com/sed.xml?eu=potenti&magna=in&vulputate=eleifend&luctus=quam&cum=a&sociis=odio&natoque=in&penatibus=hac&et=habitasse&magnis=platea&dis=dictumst&parturient=maecenas&montes=ut&nascetur=massa&ridiculus=quis&mus=augue&vivamus=luctus&vestibulum=tincidunt&sagittis=nulla&sapien=mollis&cum=molestie&sociis=lorem&natoque=quisque&penatibus=ut&et=erat&magnis=curabitur&dis=gravida&parturient=nisi&montes=at&nascetur=nibh&ridiculus=in&mus=hac&etiam=habitasse&vel=platea&augue=dictumst&vestibulum=aliquam&rutrum=augue&rutrum=quam&neque=sollicitudin&aenean=vitae&auctor=consectetuer&gravida=eget&sem=rutrum&praesent=at&id=lorem&massa=integer&id=tincidunt', 4);
insert into Course_Material (url, course_id) values ('http://simplemachines.org/ipsum/dolor/sit.html?amet=mattis&lobortis=odio&sapien=donec&sapien=vitae&non=nisi&mi=nam&integer=ultrices&ac=libero&neque=non&duis=mattis', 5);
insert into Course_Material (url, course_id) values ('http://unblog.fr/ac/enim/in/tempor.js?felis=id&ut=turpis&at=integer&dolor=aliquet&quis=massa&odio=id&consequat=lobortis&varius=convallis&integer=tortor&ac=risus&leo=dapibus&pellentesque=augue&ultrices=vel&mattis=accumsan&odio=tellus&donec=nisi&vitae=eu&nisi=orci', 6);
insert into Course_Material (url) values ('http://blinklist.com/libero.json?lacinia=in&aenean=porttitor&sit=pede&amet=justo&justo=eu&morbi=massa&ut=donec&odio=dapibus&cras=duis&mi=at&pede=velit&malesuada=eu&in=est&imperdiet=congue&et=elementum&commodo=in&vulputate=hac&justo=habitasse&in=platea&blandit=dictumst&ultrices=morbi&enim=vestibulum&lorem=velit&ipsum=id&dolor=pretium&sit=iaculis&amet=diam&consectetuer=erat&adipiscing=fermentum&elit=justo&proin=nec&interdum=condimentum&mauris=neque&non=sapien&ligula=placerat&pellentesque=ante&ultrices=nulla&phasellus=justo&id=aliquam&sapien=quis&in=turpis&sapien=eget&iaculis=elit&congue=sodales&vivamus=scelerisque');
insert into Course_Material (url) values ('https://imgur.com/sit/amet/consectetuer/adipiscing/elit.html?neque=ante&duis=nulla&bibendum=justo&morbi=aliquam');
insert into Course_Material (url) values ('https://gmpg.org/magna/vulputate/luctus.png?leo=luctus&odio=rutrum&porttitor=nulla&id=tellus&consequat=in&in=sagittis&consequat=dui&ut=vel&nulla=nisl&sed=duis&accumsan=ac&felis=nibh&ut=fusce&at=lacus&dolor=purus&quis=aliquet&odio=at&consequat=feugiat&varius=non&integer=pretium&ac=quis&leo=lectus&pellentesque=suspendisse&ultrices=potenti&mattis=in&odio=eleifend&donec=quam&vitae=a&nisi=odio&nam=in&ultrices=hac&libero=habitasse&non=platea&mattis=dictumst&pulvinar=maecenas&nulla=ut&pede=massa&ullamcorper=quis&augue=augue&a=luctus&suscipit=tincidunt&nulla=nulla&elit=mollis&ac=molestie&nulla=lorem&sed=quisque&vel=ut&enim=erat&sit=curabitur&amet=gravida&nunc=nisi&viverra=at&dapibus=nibh&nulla=in&suscipit=hac&ligula=habitasse&in=platea&lacus=dictumst&curabitur=aliquam&at=augue&ipsum=quam&ac=sollicitudin&tellus=vitae&semper=consectetuer&interdum=eget&mauris=rutrum&ullamcorper=at&purus=lorem&sit=integer&amet=tincidunt&nulla=ante');
insert into Course_Material (url) values ('https://flavors.me/potenti/nullam/porttitor.aspx?felis=est&donec=congue&semper=elementum&sapien=in&a=hac&libero=habitasse&nam=platea&dui=dictumst&proin=morbi&leo=vestibulum&odio=velit&porttitor=id&id=pretium&consequat=iaculis&in=diam&consequat=erat&ut=fermentum&nulla=justo&sed=nec&accumsan=condimentum&felis=neque&ut=sapien&at=placerat&dolor=ante&quis=nulla&odio=justo&consequat=aliquam&varius=quis&integer=turpis&ac=eget&leo=elit&pellentesque=sodales&ultrices=scelerisque&mattis=mauris&odio=sit&donec=amet&vitae=eros&nisi=suspendisse&nam=accumsan&ultrices=tortor&libero=quis&non=turpis&mattis=sed&pulvinar=ante&nulla=vivamus&pede=tortor&ullamcorper=duis&augue=mattis&a=egestas&suscipit=metus&nulla=aenean&elit=fermentum&ac=donec&nulla=ut&sed=mauris&vel=eget&enim=massa&sit=tempor&amet=convallis&nunc=nulla&viverra=neque&dapibus=libero&nulla=convallis&suscipit=eget&ligula=eleifend&in=luctus&lacus=ultricies&curabitur=eu&at=nibh&ipsum=quisque&ac=id&tellus=justo&semper=sit&interdum=amet&mauris=sapien&ullamcorper=dignissim&purus=vestibulum&sit=vestibulum&amet=ante&nulla=ipsum&quisque=primis&arcu=in&libero=faucibus&rutrum=orci&ac=luctus&lobortis=et&vel=ultrices&dapibus=posuere&at=cubilia&diam=curae&nam=nulla&tristique=dapibus&tortor=dolor');
insert into Course_Material (url) values ('http://thetimes.co.uk/blandit/nam/nulla.xml?turpis=ultrices&adipiscing=posuere&lorem=cubilia&vitae=curae&mattis=duis&nibh=faucibus&ligula=accumsan&nec=odio&sem=curabitur&duis=convallis&aliquam=duis&convallis=consequat&nunc=dui&proin=nec&at=nisi&turpis=volutpat&a=eleifend&pede=donec&posuere=ut&nonummy=dolor&integer=morbi&non=vel&velit=lectus&donec=in&diam=quam&neque=fringilla&vestibulum=rhoncus&eget=mauris&vulputate=enim&ut=leo&ultrices=rhoncus&vel=sed&augue=vestibulum&vestibulum=sit&ante=amet&ipsum=cursus&primis=id&in=turpis&faucibus=integer&orci=aliquet&luctus=massa&et=id&ultrices=lobortis&posuere=convallis&cubilia=tortor&curae=risus');
insert into Course_Material (url) values ('http://si.edu/vestibulum/ante.json?congue=pulvinar&vivamus=lobortis&metus=est&arcu=phasellus&adipiscing=sit&molestie=amet&hendrerit=erat&at=nulla&vulputate=tempus&vitae=vivamus&nisl=in&aenean=felis&lectus=eu&pellentesque=sapien&eget=cursus&nunc=vestibulum&donec=proin&quis=eu&orci=mi&eget=nulla&orci=ac&vehicula=enim&condimentum=in&curabitur=tempor&in=turpis&libero=nec&ut=euismod&massa=scelerisque&volutpat=quam');
insert into Course_Material (url) values ('https://usgs.gov/massa/id/nisl/venenatis/lacinia/aenean/sit.jsp?et=tincidunt&ultrices=lacus&posuere=at&cubilia=velit&curae=vivamus&mauris=vel&viverra=nulla&diam=eget&vitae=eros&quam=elementum&suspendisse=pellentesque&potenti=quisque&nullam=porta&porttitor=volutpat&lacus=erat&at=quisque&turpis=erat&donec=eros&posuere=viverra&metus=eget&vitae=congue&ipsum=eget&aliquam=semper&non=rutrum&mauris=nulla&morbi=nunc&non=purus&lectus=phasellus&aliquam=in&sit=felis&amet=donec&diam=semper&in=sapien&magna=a&bibendum=libero&imperdiet=nam&nullam=dui&orci=proin&pede=leo&venenatis=odio&non=porttitor&sodales=id');
insert into Course_Material (url) values ('http://nyu.edu/ac/consequat/metus/sapien/ut/nunc.js?justo=aenean&eu=auctor&massa=gravida&donec=sem&dapibus=praesent&duis=id&at=massa&velit=id&eu=nisl&est=venenatis&congue=lacinia&elementum=aenean&in=sit&hac=amet&habitasse=justo&platea=morbi&dictumst=ut&morbi=odio&vestibulum=cras&velit=mi&id=pede&pretium=malesuada&iaculis=in&diam=imperdiet&erat=et&fermentum=commodo&justo=vulputate&nec=justo&condimentum=in&neque=blandit&sapien=ultrices&placerat=enim&ante=lorem&nulla=ipsum&justo=dolor&aliquam=sit&quis=amet&turpis=consectetuer&eget=adipiscing&elit=elit&sodales=proin&scelerisque=interdum&mauris=mauris&sit=non&amet=ligula&eros=pellentesque&suspendisse=ultrices&accumsan=phasellus&tortor=id&quis=sapien&turpis=in&sed=sapien&ante=iaculis&vivamus=congue&tortor=vivamus&duis=metus&mattis=arcu&egestas=adipiscing&metus=molestie&aenean=hendrerit&fermentum=at&donec=vulputate&ut=vitae&mauris=nisl');
insert into Course_Material (url) values ('http://time.com/nisl/ut/volutpat/sapien/arcu.jpg?euismod=orci&scelerisque=mauris&quam=lacinia&turpis=sapien&adipiscing=quis&lorem=libero&vitae=nullam&mattis=sit&nibh=amet&ligula=turpis&nec=elementum&sem=ligula&duis=vehicula&aliquam=consequat&convallis=morbi&nunc=a&proin=ipsum&at=integer&turpis=a&a=nibh&pede=in&posuere=quis&nonummy=justo&integer=maecenas&non=rhoncus&velit=aliquam&donec=lacus&diam=morbi&neque=quis&vestibulum=tortor&eget=id&vulputate=nulla&ut=ultrices&ultrices=aliquet&vel=maecenas&augue=leo&vestibulum=odio&ante=condimentum&ipsum=id&primis=luctus&in=nec&faucibus=molestie&orci=sed&luctus=justo&et=pellentesque&ultrices=viverra&posuere=pede&cubilia=ac&curae=diam&donec=cras&pharetra=pellentesque&magna=volutpat&vestibulum=dui&aliquet=maecenas&ultrices=tristique&erat=est&tortor=et&sollicitudin=tempus&mi=semper&sit=est&amet=quam&lobortis=pharetra&sapien=magna&sapien=ac&non=consequat&mi=metus&integer=sapien&ac=ut&neque=nunc&duis=vestibulum&bibendum=ante&morbi=ipsum&non=primis&quam=in&nec=faucibus&dui=orci&luctus=luctus&rutrum=et&nulla=ultrices&tellus=posuere&in=cubilia');
insert into Course_Material (url) values ('http://senate.gov/potenti/nullam/porttitor/lacus.jsp?sagittis=augue&sapien=a&cum=suscipit&sociis=nulla&natoque=elit&penatibus=ac&et=nulla&magnis=sed&dis=vel&parturient=enim');
insert into Course_Material (url) values ('http://scientificamerican.com/sed/tincidunt/eu/felis/fusce/posuere/felis.js?venenatis=a&lacinia=nibh&aenean=in');
insert into Course_Material (url) values ('https://ameblo.jp/augue/vel.aspx?in=in&hac=congue&habitasse=etiam&platea=justo&dictumst=etiam&etiam=pretium&faucibus=iaculis&cursus=justo&urna=in&ut=hac&tellus=habitasse&nulla=platea&ut=dictumst&erat=etiam&id=faucibus&mauris=cursus&vulputate=urna&elementum=ut&nullam=tellus&varius=nulla&nulla=ut&facilisi=erat&cras=id&non=mauris&velit=vulputate&nec=elementum&nisi=nullam&vulputate=varius&nonummy=nulla&maecenas=facilisi&tincidunt=cras&lacus=non&at=velit&velit=nec&vivamus=nisi&vel=vulputate&nulla=nonummy&eget=maecenas&eros=tincidunt&elementum=lacus&pellentesque=at&quisque=velit&porta=vivamus&volutpat=vel&erat=nulla&quisque=eget&erat=eros&eros=elementum&viverra=pellentesque&eget=quisque&congue=porta&eget=volutpat&semper=erat&rutrum=quisque&nulla=erat&nunc=eros&purus=viverra&phasellus=eget&in=congue&felis=eget&donec=semper&semper=rutrum&sapien=nulla&a=nunc&libero=purus&nam=phasellus&dui=in&proin=felis&leo=donec&odio=semper&porttitor=sapien&id=a&consequat=libero&in=nam&consequat=dui&ut=proin&nulla=leo&sed=odio&accumsan=porttitor&felis=id&ut=consequat&at=in&dolor=consequat&quis=ut&odio=nulla&consequat=sed&varius=accumsan&integer=felis&ac=ut&leo=at');
insert into Course_Material (url) values ('https://t-online.de/auctor/gravida/sem/praesent/id/massa/id.aspx?luctus=natoque&et=penatibus&ultrices=et&posuere=magnis&cubilia=dis&curae=parturient&duis=montes&faucibus=nascetur&accumsan=ridiculus&odio=mus&curabitur=vivamus&convallis=vestibulum&duis=sagittis&consequat=sapien&dui=cum&nec=sociis&nisi=natoque&volutpat=penatibus&eleifend=et&donec=magnis&ut=dis&dolor=parturient&morbi=montes&vel=nascetur&lectus=ridiculus&in=mus&quam=etiam&fringilla=vel&rhoncus=augue&mauris=vestibulum&enim=rutrum&leo=rutrum&rhoncus=neque&sed=aenean&vestibulum=auctor&sit=gravida&amet=sem&cursus=praesent&id=id&turpis=massa&integer=id&aliquet=nisl&massa=venenatis&id=lacinia');
